version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  # Spring Boot Application Service
  spring-app:
    image: haifalaabidi/dockerhub
    container_name: SpringBack
    restart:  on-failure
    ports:
      - "8282:8282"
    depends_on:
      - mysqldb
    volumes:
     db:

