version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image: haifalaabidi/dockerhub:SpringImage
    restart: on-failure
    ports:
      - "8082:8082"
volumes:
  db: